### ISSUE TITLE
Error launching "sizer" 

### ISSUE THREAD

**Issue by kunalg123** [abk-openroad/TritonSizer#2]
Hi,

I just installed TritonSizer using steps mentioned in README, but while launching, I am getting below error. I have installed on Ubuntu. Should that be ok?

kunalg@kunalg-VirtualBox ~/Desktop/work/tools/TritonSizer/TritonSizer/src $ ./sizer 
./sizer: error while loading shared libraries: libtcl8.4.so: cannot open shared object file: No such file or directory

**Comment by kunalg123** [comment]
Attaching log file for installation. The error still exists. Please let me know if I am missing anything
[output.log](https://github.com/abk-openroad/TritonSizer/files/2682721/output.log)

**Comment by kunalg123** [comment]
Hi
I tried on another machine, but still the same error. Here are my machine details:
kunalg@kunalg-VirtualBox:~/vsdflow/work/tools/TritonSizer/src$ uname -a
Linux kunalg-VirtualBox 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mgwoo** [comment]
It seems that your compile was successful..
Could you give me the below result after you type '$ source load.sh' ?

    echo $LD_LIBRARY_PATH
    echo $PATH

**Comment by kunalg123** [comment]
kunalg@kunalg-VirtualBox:/vsdflow/work/tools/TritonSizer$ echo $LD_LIBRARY_PATH
:/home/kunalg/vsdflow/work/tools/TritonSizer/module/tcl/unix/install-sp/lib:/home/kunalg/vsdflow/work/tools/TritonSizer/module/tcl/unix/install-sp/lib

kunalg@kunalg-VirtualBox:/vsdflow/work/tools/TritonSizer$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by mgwoo** [comment]
Could you check that libtcl8.4.so is located in /home/kunalg/vsdflow/work/tools/TritonSizer/module/tcl/unix/install-sp/lib ?

The compile log says that your libtcl8.4.so is located in
/home/kunalg/Desktop/work/tools/TritonSizer/TritonSizer/module/tcl/unix/install-sp/lib/

I think you should have executed load.sh in the /home/kunalg/Desktop/work/tools/TritonSizer/TritonSizer/ folder.

Make sure that your environment variable($LD_LIBRARY_PATH) is correct.

closed.
